dnf = [
  "ModemManager",
  "NetworkManager",
  "NetworkManager-adsl",
  "NetworkManager-bluetooth",
  "NetworkManager-config-connectivity-fedora",
  "NetworkManager-openconnect-gnome",
  "NetworkManager-openvpn-gnome",
  "NetworkManager-ppp",
  "NetworkManager-ssh-gnome",
  "NetworkManager-vpnc-gnome",
  "NetworkManager-wifi",
  "NetworkManager-wwan",
  "PackageKit-command-not-found",
  "PackageKit-gstreamer-plugin",
  "PackageKit-gtk3-module",
  "aajohan-comfortaa-fonts",
  "abrt-cli",
  "abrt-desktop",
  "acl",
  "adobe-source-code-pro-fonts",
  "alsa-sof-firmware",
  "alsa-ucm",
  "alsa-utils",
  "amd-gpu-firmware",
  "amd-ucode-firmware",
  "anaconda-install-env-deps",
  "anaconda-live",
  "at",
  "at-spi2-atk",
  "at-spi2-core",
  "atheros-firmware",
  "attr",
  "audit",
  "authselect",
  "autoconf",
  "automake",
  "avahi",
  "b43-fwcutter",
  "b43-openfwwf",
  "baobab",
  "bash",
  "bash-color-prompt",
  "bash-completion",
  "bc",
  "bind-utils",
  "binutils",
  "bison",
  "bluez-cups",
  "brcmfmac-firmware",
  "brltty",
  "btrfs-assistant",
  "btrfs-progs",
  "byacc",
  "bzip2",
  "ccache",
  "chrony",
  "cifs-utils",
  "cirrus-audio-firmware",
  "colord",
  "compsize",
  "coreutils",
  "cpio",
  "crontabs",
  "cryptsetup",
  "cscope",
  "ctags",
  "cups",
  "cups-browsed",
  "cups-filters",
  "cups-pk-helper",
  "curl",
  "cyrus-sasl-plain",
  "dbus",
  "dconf",
  "decibels",
  "default-editor",
  "default-fonts-cjk-mono",
  "default-fonts-cjk-sans",
  "default-fonts-cjk-serif",
  "default-fonts-core-emoji",
  "default-fonts-core-math",
  "default-fonts-core-mono",
  "default-fonts-core-sans",
  "default-fonts-core-serif",
  "default-fonts-other-mono",
  "default-fonts-other-sans",
  "default-fonts-other-serif",
  "deltarpm",
  "desktop-backgrounds-gnome",
  "diffstat",
  "dnf5",
  "dnf5-plugins",
  "dnsmasq",
  "dos2unix",
  "dosfstools",
  "doxygen",
  "dracut-config-rescue",
  "dracut-live",
  "dracut-network",
  "e2fsprogs",
  "ed",
  "efibootmgr",
  "elfutils",
  "ethtool",
  "exfatprogs",
  "fastfetch",
  "fedora-bookmarks",
  "fedora-chromium-config",
  "fedora-flathub-remote",
  "fedora-release-workstation",
  "fedora-workstation-backgrounds",
  "fedora-workstation-repositories",
  "file",
  "filesystem",
  "firefox",
  "firewalld",
  "fish",
  "flatseal",
  "flex",
  "fpaste",
  "fprintd-pam",
  "fwupd",
  "gamemode",
  "gcc",
  "gcc-c++",
  "gdb",
  "gdm",
  "gettext",
  "ghostscript",
  "git",
  "glib-networking",
  "glibc",
  "glibc-all-langpacks",
  "glibc-devel",
  "glycin-thumbnailer",
  "gnome-backgrounds",
  "gnome-bluetooth",
  "gnome-boxes",
  "gnome-browser-connector",
  "gnome-calculator",
  "gnome-calendar",
  "gnome-characters",
  "gnome-classic-session",
  "gnome-clocks",
  "gnome-color-manager",
  "gnome-connections",
  "gnome-contacts",
  "gnome-control-center",
  "gnome-disk-utility",
  "gnome-epub-thumbnailer",
  "gnome-font-viewer",
  "gnome-initial-setup",
  "gnome-logs",
  "gnome-maps",
  "gnome-remote-desktop",
  "gnome-session-wayland-session",
  "gnome-settings-daemon",
  "gnome-shell",
  "gnome-shell-extension-background-logo",
  "gnome-software",
  "gnome-system-monitor",
  "gnome-text-editor",
  "gnome-user-docs",
  "gnome-user-share",
  "gnome-weather",
  "gnupg2",
  "grub2-efi-ia32",
  "grub2-efi-ia32-cdboot",
  "grub2-efi-ia32-modules",
  "grub2-efi-x64",
  "grub2-efi-x64-cdboot",
  "grub2-efi-x64-modules",
  "grub2-pc",
  "grub2-tools",
  "grub2-tools-efi",
  "grub2-tools-extra",
  "grubby",
  "gstreamer1-plugin-dav1d",
  "gstreamer1-plugin-libav",
  "gstreamer1-plugins-bad",
  "gstreamer1-plugins-good",
  "gstreamer1-plugins-ugly",
  "gutenprint",
  "gutenprint-cups",
  "gvfs-afc",
  "gvfs-afp",
  "gvfs-archive",
  "gvfs-fuse",
  "gvfs-goa",
  "gvfs-gphoto2",
  "gvfs-mtp",
  "gvfs-smb",
  "hfsplus-tools",
  "hostname",
  "hplip",
  "hunspell",
  "hyperv-daemons",
  "ibus-anthy",
  "ibus-chewing",
  "ibus-gtk3",
  "ibus-gtk4",
  "ibus-hangul",
  "ibus-libpinyin",
  "ibus-m17n",
  "ibus-typing-booster",
  "indent",
  "inotify-tools",
  "intel-audio-firmware",
  "intel-gpu-firmware",
  "intel-vsc-firmware",
  "iproute",
  "iptables-nft",
  "iptstate",
  "iputils",
  "irqbalance",
  "iscsi-initiator-utils",
  "isomd5sum",
  "iwlegacy-firmware",
  "iwlwifi-dvm-firmware",
  "iwlwifi-mvm-firmware",
  "kbd",
  "kbd-legacy",
  "kernel",
  "kernel-core",
  "kernel-modules",
  "kernel-modules-extra",
  "kexec-tools",
  "langpacks-core-en_GB",
  "langpacks-en_GB",
  "less",
  "libdnf5-plugin-actions",
  "libertas-firmware",
  "libglvnd-gles",
  "librsvg2",
  "libsane-hpaio",
  "libtool",
  "libva-intel-media-driver",
  "linux-firmware",
  "livesys-scripts",
  "localsearch",
  "logrotate",
  "loupe",
  "lrzsz",
  "lsof",
  "ltrace",
  "lvm2",
  "mactel-boot",
  "mailcap",
  "make",
  "man-db",
  "man-pages",
  "mcelog",
  "mdadm",
  "mediawriter",
  "mesa-dri-drivers",
  "mesa-libEGL",
  "mesa-vulkan-drivers",
  "microcode_ctl",
  "mpage",
  "mt7xxx-firmware",
  "mtr",
  "nautilus",
  "ncurses",
  "net-tools",
  "nfs-utils",
  "nmap-ncat",
  "nss-mdns",
  "ntfs-3g",
  "ntfsprogs",
  "nvidia-gpu-firmware",
  "nvme-cli",
  "nxpwireless-firmware",
  "open-vm-tools-desktop",
  "opensc",
  "openssh-clients",
  "openssh-server",
  "orca",
  "pam_afs_session",
  "papers",
  "papers-nautilus",
  "paps",
  "parted",
  "passwdqc",
  "patch",
  "patchutils",
  "pciutils",
  "perf",
  "pinentry-gnome3",
  "pinfo",
  "pipewire-alsa",
  "pipewire-config-raop",
  "pipewire-gstreamer",
  "pipewire-pulseaudio",
  "pipewire-utils",
  "pkgconf",
  "plocate",
  "plymouth",
  "plymouth-system-theme",
  "podman",
  "policycoreutils",
  "policycoreutils-python-utils",
  "polkit",
  "prefixdevname",
  "procps-ng",
  "psacct",
  "psmisc",
  "ptyxis",
  "qadwaitadecorations-qt5",
  "qcom-wwan-firmware",
  "qemu-guest-agent",
  "qt5-qtbase",
  "qt5-qtbase-gui",
  "qt5-qtdeclarative",
  "qt5-qtxmlpatterns",
  "quota",
  "realmd",
  "realtek-firmware",
  "rootfiles",
  "rpm",
  "rsync",
  "rsyslog",
  "rygel",
  "samba-client",
  "sane-backends-drivers-scanners",
  "selinux-policy-targeted",
  "setup",
  "shadow-utils",
  "shim-ia32",
  "shim-x64",
  "showtime",
  "simple-scan",
  "smartmontools",
  "snapper",
  "snapshot",
  "sos",
  "speech-dispatcher",
  "spice-vdagent",
  "spice-webdavd",
  "sssd-common",
  "sssd-kcm",
  "sssd-proxy",
  "strace",
  "subversion",
  "sudo",
  "sushi",
  "symlinks",
  "system-config-printer-udev",
  "systemd",
  "systemd-oomd-defaults",
  "systemd-resolved",
  "systemd-udev",
  "systemtap",
  "tar",
  "tcpdump",
  "teamd",
  "terra-release",
  "terra-release-extras",
  "terra-release-mesa",
  "terra-release-multimedia",
  "thermald",
  "time",
  "tinysparql",
  "tiwilink-firmware",
  "toolbox",
  "totem-video-thumbnailer",
  "traceroute",
  "tree",
  "udisks2-btrfs",
  "unzip",
  "uresourced",
  "usb_modeswitch",
  "usbutils",
  "util-linux",
  "valgrind",
  "vim-minimal",
  "virtualbox-guest-additions",
  "vte-profile",
  "wget2-wget",
  "which",
  "whois",
  "wireplumber",
  "words",
  "wpa_supplicant",
  "xdg-desktop-portal",
  "xdg-desktop-portal-gnome",
  "xdg-desktop-portal-gtk",
  "xdg-user-dirs-gtk",
  "xfsprogs",
  "yadm",
  "yelp",
  "zip",
  "zram-generator-defaults",
]
